@startuml

skinparam classAttributeIconSize 0
skinparam defaultFontName Consolas
!pragma useIntermediatePackages false

class SokobanApp {
}

package model {
    abstract class Board {
    }

    class Board4Play {
    }

    Board <|-- Board4Play

    class Board4Design {
    }

    Board <|-- Board4Design

    abstract class Grid {
    }

    class Grid4Play {
    }

    Grid <|-- Grid4Play

    class Grid4Design {
    }

    Grid <|-- Grid4Design

    abstract class Cell {
    }

    class Cell4Play {
    }

    Cell <|-- Cell4Play

    class Cell4Design {
    }

    Cell <|-- Cell4Design

    class ElementStack {
    }

    class ElementStack4Play {
    }

    ElementStack <|-- ElementStack4Play

    class ElementStack4Design {
    }

    ElementStack <|-- ElementStack4Design

    abstract class GameObject {
    }

    class Wall {
    }

    GameObject <|-- Wall

    class Box {
    }

    GameObject <|-- Box

    class Player {
    }

    GameObject <|-- Player

    class Target {
    }

    GameObject <|-- Target

    class Ground {
    }

    GameObject <|-- Ground
}



@enduml