@startuml

skinparam classAttributeIconSize 0
skinparam defaultFontName Consolas
!pragma useIntermediatePackages false

class Game {
    -board: Board
    +getBoard()
}

class Board {
    -grid: Grid
    +getGrid()
}

class Grid {
    -width: int
    -height: int
    -list<list<Cell>>
    +getWidth() : int
    +getHeight() : int
    +getCell(int x, int y) : Cell
}

class Cell {
    +set() : void
    +isMultipleLayer() : Boolean
}

abstract class GameObject {
}

abstract class Element {
}

class ElementStack {}

class Wall {
}

class Box {
}

class Player {
}

class Target {
}

class Ground {
}

Game *-left-> "1" Board
Board *-left-> "1" Grid
Grid *-down-> "1" Cell

ElementStack *-left-> "0..1" Cell



ElementStack *-down-> "1..3" GameObject
GameObject <|-right- Box
GameObject <|-down- Target
GameObject <|-down- Player
GameObject <|-down- Ground

Element *-up-> "0..1" Cell
Element <|-left- Wall
Element <|-right- GameObject


@enduml